version: '3.3'
services:
  mongo: 
    image: mongo:4.1-xenial

    volumes:
      - ./db:/data/db
      - ./dump:/dump

    networks:
      - yapi-net

  yapi:
    image: my_yapi

    networks:
      - yapi-net
      - proxy-net

    depends_on:
      - mongo

networks:
  yapi-net:
    driver: bridge
  proxy-net:
    external:
      name: nginx_proxy-net