version: '3.3'
services:
  mongo: 
    image: mongo:4.1-xenial

    environment:
      MONGO_INITDB_ROOT_USERNAME: yapi-admin
      MONGO_INITDB_ROOT_PASSWORD: 2zz3ej

    volumes:
      - ./db:/var/lib/mongodb

    networks:
      - yapi-net

  yapi:
    image: my_yapi

    networks:
      - yapi-net
      - proxy-net

    depends_on:
      - mongo

networks:
  yapi-net:
    driver: bridge
  proxy-net:
    external:
      name: nginx_proxy-net