version: '3.3'
services:
  mongo: 
    image: mongo:4.1-xenial

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    volumes:
      - ./db:/var/lib/mongodb

    networks:
      - yapi-net

  yapi:
    image: my_yapi

    networks:
      - yapi-net

    depends_on:
      - mongo

networks:
  yapi-net:
    driver: bridge